import { Poppins } from "next/font/google";
import "./globals.css";
import BackToTopButton from "../../src/components/shared/back-to-top/BackToTop";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "600"] });

export const metadata = {
  title: "Pibicy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="max-w-full mx-auto bg-white ">
          {children}
          <BackToTopButton />
        </div>
      </body>
    </html>
  );
}
